apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "hobbes"
  name: "events"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: "RollingUpdate"
  selector:
    matchLabels:
      app: "events"
  template:
    metadata:
      labels:
        app: "events"
    spec:
      imagePullSecrets:
        - name: hobbes
      containers:
        - name: "events"
          image: "registry.digitalocean.com/hobbes/ibkr-events:latest"
          imagePullPolicy: "Always"
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 15
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            ## total 25 seconds to allow for startup
            failureThreshold: 5
            periodSeconds: 5
          resources:
            limits:
              cpu: "500m"
              memory: "500Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: HOBBES_CHANNEL_EP
              valueFrom:
                configMapKeyRef:
                  key: "hobbes.channel.endpoint"
                  name: "events"
            - name: FWD_TARGET
              valueFrom:
                secretKeyRef:
                  key: "example"
                  name: "events"