apiVersion: v1
kind: Service
metadata:
  namespace: "hobbes"
  name: "events"
spec:
  type: ClusterIP
  selector:
    app: "events"
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080