---
apiVersion: v1
kind: Namespace
metadata:
  name: hobbes
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: hobbes
  name: science-sp500
data:
  science.kind: "market"
  science.market: "sp500_dow"
---
apiVersion: v1
kind: Secret
metadata:
  namespace: hobbes
  name: science-sp500
data:
  example: "dGVzdA=="
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: hobbes
  name: science-sp500
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 60
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      activeDeadlineSeconds: 1800
      template:
        spec:
          imagePullSecrets:
            - name: hobbes
          restartPolicy: Never
          containers:
            - name: science-sp500
              image: registry.digitalocean.com/hobbes/science:latest
              imagePullPolicy: Always
              resources:
                limits:
                  cpu: 750m
                  memory: 950Mi
                requests:
                  cpu: 100m
                  memory: 200Mi
              env:
                - name: kind
                  valueFrom:
                    configMapKeyRef:
                      key: science.kind
                      name: science-sp500
                - name: target
                  valueFrom:
                    configMapKeyRef:
                      key: science.market
                      name: science-sp500
