---
apiVersion: v1
kind: Service
metadata:
  name: "swagger-ui"
spec:
  selector:
    app: "swagger-ui"
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: "swagger-ui"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "swagger-ui"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: "RollingUpdate"
  selector:
    matchLabels:
      app: "swagger-ui"
  template:
    metadata:
      labels:
        app: "swagger-ui"
    spec:
      containers:
        - name: "swagger-ui"
          image: "localhost:5000/swagger-ui:latest"
          imagePullPolicy: "Always"
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 250m
              memory: 250Mi
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: API_URL
              value: "gateway.yaml"