openapi: "3.0.0"
info:
  version: 1.0.0
  title: IBKR Gateway
  license:
    name: MIT
servers:
  - url: http://localhost:35081/function/ibkr-gateway
paths:
  /:
    post:
      summary: IBKR Gateway Function
      operationId: ibkr-gateway
      tags:
        - ibkr-gateway
      parameters:
        - name: type
          in: path
          required: true
          description: The type of operation to invoke
          schema:
            type: string
            enum: 
              - health-check
              - auth-check
              - portfolio-get-accounts
              - portfolio-get-positions
              - orders-preview
              - orders-place
              - orders-list
              - market-data
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
        default:
          description: unexpected error
          content:
            text/plain:
              schema:
                type: string
  /?type=auth-check:
    post:
      summary: IBKR Gateway AuthCheck
      operationId: auth-check
      tags:
        - ibkr-gateway
        - auth-check
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Err
          content:
            text/plain:
              schema:
                type: string
        default:
          description: Err
          content:
            text/plain:
              schema:
                type: string
  /?type=health-check:
    post:
      summary: IBKR Gateway HealthCheck
      operationId: health-check
      tags:
        - ibkr-gateway
        - health-check
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
        '503':
          description: Unhealthy
          content:
            text/plain:
              schema:
                type: string
        default:
          description: Err
          content:
            text/plain:
              schema:
                type: string
  /?type=market-data:
    post:
      operationId: market-data
      summary: Gets historical market data for a stock symbol
      tags:
        - ibkr-gateway
        - market-data
      consumes:
        - application/json
      requestBody:
        description: 'Passed in parameters for: test'
        content:
          application/json:
            schema:
              $ref: "#/definitions/MarketDataGetRequest"
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
        default:
          description: Err
          content:
            text/plain:
              schema:
                type: string
  
definitions:
  PortfolioGetPositionsRequest:
    type: object
    required:
      - symbol
    properties:
      symbol:
        type: string
        description: The stock symbol per NYSE
  OrderRequest:
    type: object
    required:
      - symbol
      - buyOrSell
      - quantity
    properties:
      symbol:
        type: string
        description: The stock symbol per NYSE
      buyOrSell:
        type: string
        enum:
          - BUY
          - SELL
        description: Whether to buy or sell
      quantity:
        type: number
        format: float
        minimum: 1.0
        maximum: 2000.0
        description: The quantity of the stock to BUY or SELL
  MarketDataGetRequest:
    type: object
    required:
      - symbol
      - bar
      - period
    properties:
      symbol:
        type: string
      bar:
        type: string
        enum:
          - 1min 
          - 2min 
          - 3min 
          - 5min 
          - 10min 
          - 15min 
          - 30min 
          - 1h 
          - 2h 
          - 3h 
          - 4h 
          - 8h 
          - 1d 
          - 1w 
          - 1m
      period:
        type: string
