apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-broker-config
  namespace: knative-eventing
data:
  default.topic.partitions: "3"
  default.topic.replication.factor: "1"
  bootstrap.servers: "hobbes-kafka-cluster-kafka-bootstrap.kafka:9092"